{%- comment -%}
  Include as: {%- include_cached favicon.html -%}
  Depends on: site.static_files.
  Results in: HTML for links to favicon files. Favicons originally generated by
    https://realfavicongenerator.net/.
  Overwrites: 
    file.
  
  This file replaces the default favicon logic with super fancy favicons.
{%- endcomment -%}

<link rel="apple-touch-icon" sizes="180x180" href="{{ 'apple-touch-icon.png' | prepend: '/images/favicons/c' | relative_url }}">
<link rel="icon" type="image/png" sizes="32x32" href="{{ 'favicon-32x32.png' | prepend: '/images/favicons/' | relative_url }}">
<link rel="icon" type="image/png" sizes="16x16" href="{{ 'favicon-16x16.png' | prepend: '/images/favicons/' | relative_url }}">
<link rel="manifest" href="{{ 'site.webmanifest' | prepend: '/images/favicons/' | relative_url }}">
<link rel="mask-icon" href="{{ 'safari-pinned-tab.svg' | prepend: '/images/favicons/' | relative_url }}" color="#6cc04a">
<link rel="shortcut icon" href="{{ 'favicon.ico' | prepend: '/images/favicons/' | relative_url }}">
<meta name="msapplication-TileColor" content="#6cc04a">
<meta name="msapplication-config" content="{{ 'browserconfig.xml' | prepend: '/images/favicons/' | relative_url }}">
<meta name="theme-color" content="#6cc04a">