name: Links

on:
  repository_dispatch:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  schedule:
    - cron: "00 18 * * *"

jobs:
  linkChecker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Link Checker
        id: lychee
        uses: lycheeverse/lychee-action@v1.9.3
        with:
          fail: true
          args: --base './docs/_site' --verbose --no-progress './**/*.html' './**/*.rst'
          # --base <BASE> Base URL or website root directory to check relative URLs e.g. https://example.com or `/path/to/public`

      - name: Create Issue From File
        if: env.lychee_exit_code != 0
        uses: peter-evans/create-issue-from-file@v4
        with:
          title: Link Checker Report
          content-filepath: ./lychee/out.md
          labels: report, automated issue
